//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProfGames.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Viktorina
    {
        public int Kategotiya_1 { get; set; }
        public int Kategotiya_2 { get; set; }
        public int Kategotiya_3 { get; set; }
    
        public virtual Voprosi_History_of_the_IT_sphere Voprosi_History_of_the_IT_sphere { get; set; }
        public virtual Voprosi_IT Voprosi_IT { get; set; }
        public virtual Voprosi_People_in_Programming Voprosi_People_in_Programming { get; set; }
    }
}
