//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProfGames.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voprosi_IT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Voprosi_IT()
        {
            this.Viktorina = new HashSet<Viktorina>();
        }
    
        public int @int { get; set; }
        public string Vopros_1 { get; set; }
        public string Vopros_2 { get; set; }
        public string Vopros_3 { get; set; }
        public string Vopros_4 { get; set; }
        public string Vopros_5 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Viktorina> Viktorina { get; set; }
    }
}
